// <auto-generated />
using DataGen_v1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataGen_v1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataGen_v1.Models.ApiConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HeaderName")
                        .HasColumnType("text");

                    b.Property<string>("HeaderValue")
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApiConfigs");
                });

            modelBuilder.Entity("DataGen_v1.Models.DbConnectionConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DbConfigs");
                });

            modelBuilder.Entity("DataGen_v1.Models.Generator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApiConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("DbConnectionConfigId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TableName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApiConfigId");

                    b.HasIndex("DbConnectionConfigId");

                    b.ToTable("Generators");
                });

            modelBuilder.Entity("DataGen_v1.Models.NodeConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DataType")
                        .HasColumnType("integer");

                    b.Property<string>("FixedValue")
                        .HasColumnType("text");

                    b.Property<int>("GeneratorId")
                        .HasColumnType("integer");

                    b.Property<double?>("MaxRange")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinRange")
                        .HasColumnType("double precision");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("ValueList")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GeneratorId");

                    b.HasIndex("ParentId");

                    b.ToTable("NodeConfigs");
                });

            modelBuilder.Entity("DataGen_v1.Models.Generator", b =>
                {
                    b.HasOne("DataGen_v1.Models.ApiConfig", "ApiConfig")
                        .WithMany()
                        .HasForeignKey("ApiConfigId");

                    b.HasOne("DataGen_v1.Models.DbConnectionConfig", "DbConnectionConfig")
                        .WithMany()
                        .HasForeignKey("DbConnectionConfigId");

                    b.Navigation("ApiConfig");

                    b.Navigation("DbConnectionConfig");
                });

            modelBuilder.Entity("DataGen_v1.Models.NodeConfig", b =>
                {
                    b.HasOne("DataGen_v1.Models.Generator", "Generator")
                        .WithMany()
                        .HasForeignKey("GeneratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataGen_v1.Models.NodeConfig", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Generator");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DataGen_v1.Models.NodeConfig", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
